name: Deploy MultiK8s

on:
  push:
    branches:
      - master

env:
  SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t z82615566/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true z82615566/react-test npm test

      - name: Set Service Key
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: k8stest-478013

      - name: Debug Cloud
        run: |
          gcloud --version
          gcloud auth list
          gcloud config get-value project

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: k8stest
          location: asia-east1

      - name: Build
        run: |-
          docker build \
          -t asia-docker.pkg.dev/k8stest-478013/multik8s-repo/multi-client-gh:latest \
          -t asia-docker.pkg.dev/k8stest-478013/multik8s-repo/multi-client-gh:${{ env.SHA }} \
          -f ./client/Dockerfile \
          ./client 

      - name: Push
        run: |-
          docker push asia-docker.pkg.dev/k8stest-478013/multik8s-repo/multi-client-gh:latest
          docker push asia-docker.pkg.dev/k8stest-478013/multik8s-repo/multi-client-gh:${{ env.SHA }}     

